use_frameworks!

platform :ios, '8.0'

target 'ZhangHongBaseModule_Example' do
  pod 'ZhangHongBaseModule', :path => '../'

  target 'ZhangHongBaseModule_Tests' do
    inherit! :search_paths

    
  end
end
